/* cr_user.sql */
-- used to create user for EBR demonstration

CREATE USER hr IDENTIFIED BY Ora#42_dbP;

ALTER USER hr DEFAULT TABLESPACE USERS
              QUOTA UNLIMITED ON USERS;

ALTER USER hr TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO hr;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE , UNLIMITED TABLESPACE TO hr;

-- for using DBMS_REDEFINITION
GRANT CREATE MATERIALIZED VIEW TO HR;
GRANT EXECUTE ON DBMS_REDEFINITION TO HR;



