# ac_replay.properties
# config file for ACDemo java program
#  specifically for testing TAC / Application Continuity enabled

# Use replay datasource this is critical setting
datasource=oracle.jdbc.replay.OracleDataSourceImpl

# Set verbose mode
VERBOSE=FALSE

# database JDBC URL NOTE: service name here is one with TAC enabled
url=jdbc:oracle:thin:@(DESCRIPTION=(CONNECT_TIMEOUT=90)(RETRY_COUNT=50)(RETRY_DELAY=3)(TRANSPORT_CONNECT_TIMEOUT=3)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=crs01-scan.gg.wi.rr.com)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=hr_tac)))

# database username and password:
username=hr
password=Oracle_4U

# Enable FAN
fastConnectionFailover=TRUE

#Disable connection tests
validateConnectionOnBorrow=TRUE

# number of connections in the UCP's pool:
ucp_pool_size=30

#Connection Wait Timeout in S for busy pool
connectionWaitTimeout=5

# number of active threads (this simulates concurrent load):
number_of_threads=10

# think time in ms is how much time the threads will sleep before looping:
thread_think_time=50

# enable AC replay statistics
print_ac_stats=TRUE
