#!/bin/bash

JAVA_HOME=${ORACLE_HOME}/jdk
JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

if [[ -z "${JAVA_HOME}" ]]; then
    read -p "Enter Java Home: " JAVA_HOME
    export JAVA_HOME=${JAVA_HOME}
fi

${JAVA_HOME}/bin/java -classpath ./lib/acdemo.jar:./lib/ucp17.jar:./lib/ojdbc17.jar:./lib/ons.jar acdemo.ACDemo ac_replay.properties
