# watchfan.properties
#   config file for WatchFan java program

# onsConnect [ LOCAL | REMOTE ]
#   LOCAL connect is if you run this program on the RAC server, be sure to 
#     update the oracle.ons.oraclehome to match your GRID_HOME
onsConnect=REMOTE
oracle.ons.oraclehome=/u01/app/19/grid_1

# REMOTE will connect to a remote ONS server, this assumes clear connection without SSL / TLS
# onsNodes A comma separated list of host:port pairs of ONS daemons with which the ONS runtime in this Java VM should communicate.
#  Note default remote port is 6200
onsNodes=srvr01.gg.wi.rr.com:6200,srvr02.gg.wi.rr.com:6200

# Name of the databae service to be monitored
serviceName=hr_tac

