
  CREATE OR REPLACE EDITIONABLE TRIGGER "HR_TST"."SECURE_EMPLOYEES" 
  BEFORE INSERT OR UPDATE OR DELETE ON employees
BEGIN
  secure_dml;
END secure_employees;

ALTER TRIGGER "HR_TST"."SECURE_EMPLOYEES" DISABLE