#!/bin/bash
#
# instORDS.sh

ORDS_URL=https://download.oracle.com/otn_software/java/ords/ords-24.1.0.108.0942.zip
ORDS_PORT=8080
INST_DIR=/opt/ords

# Create install location
/usr/bin/sudo /usr/bin/mkdir -p "${INST_DIR}"
/usr/bin/sudo /usr/bin/chown opc:opc "${INST_DIR}"

# configure firewall for Oracle listener
/usr/bin/sudo sh -c "/usr/bin/firewall-cmd --permanent --zone=public --add-port=${ORDS_PORT}/tcp"
/usr/bin/sudo sh -c "/usr/bin/firewall-cmd --reload"

# Note need the -L option for curl to follow 302 redirects
cd "${HOME}" || exit 1
/usr/bin/curl -L -O "${ORDS_URL}"

/usr/bin/unzip -q -o -d "${INST_DIR}" "${HOME}/$( /usr/bin/basename "${ORDS_URL}" )"

ords_features="--feature-sdw true --log-folder ${ords_logs}"
ords_db="--admin-user SYS --password-stdin --db-hostname ${db_host} --db-port ${ora_lsnr_port} --db-servicename ${db_service}"
ords_storage="--schema-tablespace SYSAUX --schema-temp-tablespace TEMP"

echo ${db_password} | "${INST_DIR}/bin/ords" install ${ords_features} ${ords_db} ${ords_storage}

"${INST_DIR}/bin/ords" config set standalone.http.port ${ORDS_PORT}
"${INST_DIR}/bin/ords" config set standalone.access.log /var/log/ords

# Configure ORDS auto start
# Create configuration file
#   Note ORDS_BASE is the directory under "ords" used by systemctl start
/usr/bin/sudo /usr/bin/touch /etc/ords.conf
/usr/bin/sudo /usr/bin/chown opc:opc /etc/ords.conf
echo "# ORDS Service Script Configuration File (ords.config)" > /etc/ords.conf
echo "# Generated by instORDS.sh $( date )"                    >> /etc/ords.conf
echo "ORDS_BASE=$( dirname "${INST_DIR}" )"                   >> /etc/ords.conf
echo "ORDS_CONFIG=${ORDS_CONFIG}"                             >> /etc/ords.conf
echo "SERVE_EXTRA_ARGS=--port ${ords_port} --secure"          >> /etc/ords.conf
echo "JAVA_HOME=${JAVA_HOME}"                                 >> /etc/ords.conf
/usr/bin/chown oracle:oinstall /etc/ords.conf
/usr/bin/chmod 750 /etc/ords.conf
 
