#!/bin/bash
# runonce.sh

# simple script pulled from serverfault.com 
#  Will create a on-reboot cron entry and remove once used


SCRIPT_NAME="$( /usr/bin/basename "$0" )"

if [[ $# -eq 0 ]]; then
    echo "Schedules a command to be run after the next reboot."
    echo "Usage: ${SCRIPT_NAME} <command>"
    echo "       ${SCRIPT_NAME} -p <path> <command>"
    echo "       ${SCRIPT_NAME} -r <command>"
else
    REMOVE=0
    COMMAND=${!#}
    SCRIPTPATH=$PATH

    while getopts ":r:p:" optionName; do
        case "$optionName" in
            r) REMOVE=1; COMMAND=$OPTARG;;
            p) SCRIPTPATH=$OPTARG;;
            *) echo "Invalid option given."; exit 1;;
        esac
    done

    SCRIPT="${HOME}/.${SCRIPT_NAME}_$( echo "$COMMAND" | sed 's/[^a-zA-Z0-9_]/_/g' )"

    if [[ ! -f $SCRIPT ]]; then
        echo "PATH=$SCRIPTPATH" >> "$SCRIPT"
        echo "cd $( pwd )"        >> "$SCRIPT"
        echo "logger -t ${SCRIPT_NAME} -p local3.info \"COMMAND=$COMMAND ; USER=\$( /usr/bin/whoami ) ($( /usr/bin/logname )) ; PWD=$( pwd ) ; PATH=\$PATH\"" >> "$SCRIPT"
        echo "$COMMAND | /usr/bin/logger -t ${SCRIPT_NAME} -p local3.info" >> "$SCRIPT"
        echo "$0 -r \"$( echo "$COMMAND" | sed 's/\"/\\\"/g' )\""     >> "$SCRIPT"
        /usr/bin/chmod +x "$SCRIPT"
    fi

    CRONTAB="${HOME}/.${SCRIPT_NAME}_temp_crontab_$RANDOM"
    ENTRY="@reboot $SCRIPT"

    echo "$( /usr/bin/crontab -l 2>/dev/null )" | /usr/bin/grep -v "$ENTRY" | /usr/bin/grep -v "^# DO NOT EDIT THIS FILE - edit the master and reinstall.$" | /usr/bin/grep -v "^# ([^ ]* installed on [^)]*)$" | /usr/bin/grep -v "^# (Cron version [^$]*\$[^$]*\$)$" > "$CRONTAB"

    if [[ $REMOVE -eq 0 ]]; then
        echo "$ENTRY" >> "$CRONTAB"
    fi

    /usr/bin/crontab "$CRONTAB"
    /usr/bin/rm -f "$CRONTAB"

    if [[ $REMOVE -ne 0 ]]; then
        [[ -f "$SCRIPT" ]] && /usr/bin/rm -f "$SCRIPT"
    fi
fi

# END
