#!/bin/bash
#
# srvrSetup.sh

# setup standard server settings
DNS_SERVER=10.202.202.2
DNS_DOMAIN=cloud.oraontap.com
PROXY_SERVER=proxy01.cloud.oraontap.com
PROXY_PORT=3128

dns_file=/etc/resolv.conf

# let server setup finish
/bin/sleep 30

# setup DNS 
echo "# Generated by srvrSetup.sh" | /bin/sudo /bin/tee "${dns_file}"
echo "nameserver ${DNS_SERVER}" | /bin/sudo /bin/tee -a "${dns_file}"
echo "search ${DNS_DOMAIN}" | /bin/sudo /bin/tee -a "${dns_file}"

# setup PROXY server
# start with DNF configuration
echo "proxy=http://${PROXY_SERVER}:${PROXY_PORT}" | /bin/sudo /bin/tee -a /etc/dnf/dnf.conf

# setup proxy server for command line tools like curl
echo "" | /bin/sudo /bin/tee -a /etc/bashrc
echo "# added by srvrSetup.sh script" | /bin/sudo /bin/tee -a /etc/bashrc
echo "export http_proxy=\"http://${PROXY_SERVER}:${PROXY_PORT}\"" | /bin/sudo /bin/tee -a /etc/bashrc
echo "export https_proxy=\"http://${PROXY_SERVER}:${PROXY_PORT}\"" | /bin/sudo /bin/tee -a /etc/bashrc

# END
