
  ALTER TABLE "HR_TST"."DEPARTMENTS" ADD CONSTRAINT "DEPT_LOC_FK" FOREIGN KEY ("LOCATION_ID")
	  REFERENCES "HR_TST"."LOCATIONS" ("LOCATION_ID") ENABLE;
  ALTER TABLE "HR_TST"."DEPARTMENTS" ADD CONSTRAINT "DEPT_MGR_FK" FOREIGN KEY ("MANAGER_ID")
	  REFERENCES "HR_TST"."EMPLOYEES" ("EMPLOYEE_ID") ENABLE;