
set echo on

EXEC DBMS_STATS.SET_TABLE_PREFS('PERFLAB', 'EMPLOYEES', 'STALE_PERCENT', '12');

COL OWNER FORMAT a10
COL TABLE_NAME FORMAT a20
COL PREFERENCE_NAME FORMAT a24
COL PREFERENCE_VALUE FORMAT a40
SELECT * FROM DBA_TAB_STAT_PREFS WHERE OWNER = 'PERFLAB';
